version: "3"

networks:
  expense:

volumes:
  mysql:

services:
  mysql:
    image:
    container_name:
    volume:
      - mysql:/
  
  backend:
    image:
    container_name:
    command: sh -c "sleep 10 && node /app/index.js "
    depends_on:
    - mysql
  
  frontend:
    image:
    container_name:
    ports:
      - "80:80"
    depends_on:
    - backend